server:
  port: 8082
spring.data.mongodb:
  database: SA-school
  uri: mongodb://localhost:27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: SchoolService
