server:
  port: 8085
spring.data.mongodb:
  database: avatars
  uri: mongodb://localhost:27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: AvatarService
