server:
  port: 8091
spring.data.mongodb:
  database: elements
  uri: mongodb://localhost:27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ElementCommandService
